// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyCapability(arg1) {
  return window['go']['desktop']['App']['ApplyCapability'](arg1);
}

export function ApplyFileWrite(arg1) {
  return window['go']['desktop']['App']['ApplyFileWrite'](arg1);
}

export function ApplyKnowledgeReviewBatch(arg1) {
  return window['go']['desktop']['App']['ApplyKnowledgeReviewBatch'](arg1);
}

export function ApplyModelProfile(arg1) {
  return window['go']['desktop']['App']['ApplyModelProfile'](arg1);
}

export function ApplyQARegressionSourceWrite(arg1) {
  return window['go']['desktop']['App']['ApplyQARegressionSourceWrite'](arg1);
}

export function ApproveQARegressionSourcePatchApplyPlan(arg1) {
  return window['go']['desktop']['App']['ApproveQARegressionSourcePatchApplyPlan'](arg1);
}

export function ApproveQARegressionTestDraft(arg1) {
  return window['go']['desktop']['App']['ApproveQARegressionTestDraft'](arg1);
}

export function ArchiveJob(arg1) {
  return window['go']['desktop']['App']['ArchiveJob'](arg1);
}

export function Ask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['App']['Ask'](arg1, arg2, arg3, arg4, arg5);
}

export function Chat(arg1, arg2) {
  return window['go']['desktop']['App']['Chat'](arg1, arg2);
}

export function CompleteSetup(arg1) {
  return window['go']['desktop']['App']['CompleteSetup'](arg1);
}

export function ConnectorRegistry() {
  return window['go']['desktop']['App']['ConnectorRegistry']();
}

export function CreateJob(arg1) {
  return window['go']['desktop']['App']['CreateJob'](arg1);
}

export function CreateSkillFromSession(arg1) {
  return window['go']['desktop']['App']['CreateSkillFromSession'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['desktop']['App']['DeleteConversation'](arg1);
}

export function DeleteExtension(arg1) {
  return window['go']['desktop']['App']['DeleteExtension'](arg1);
}

export function DeleteMemory(arg1) {
  return window['go']['desktop']['App']['DeleteMemory'](arg1);
}

export function DismissNotification(arg1) {
  return window['go']['desktop']['App']['DismissNotification'](arg1);
}

export function DraftKnowledgeProposal(arg1) {
  return window['go']['desktop']['App']['DraftKnowledgeProposal'](arg1);
}

export function DraftModelProfileFromConversation(arg1) {
  return window['go']['desktop']['App']['DraftModelProfileFromConversation'](arg1);
}

export function EditUserMessage(arg1, arg2) {
  return window['go']['desktop']['App']['EditUserMessage'](arg1, arg2);
}

export function ExplainReplayTrace(arg1) {
  return window['go']['desktop']['App']['ExplainReplayTrace'](arg1);
}

export function ExportSkill(arg1, arg2) {
  return window['go']['desktop']['App']['ExportSkill'](arg1, arg2);
}

export function ExportTrajectory(arg1) {
  return window['go']['desktop']['App']['ExportTrajectory'](arg1);
}

export function ExtensionFailures(arg1) {
  return window['go']['desktop']['App']['ExtensionFailures'](arg1);
}

export function GenerateCapability(arg1) {
  return window['go']['desktop']['App']['GenerateCapability'](arg1);
}

export function GenerateExtension(arg1) {
  return window['go']['desktop']['App']['GenerateExtension'](arg1);
}

export function GenerateModel(arg1, arg2) {
  return window['go']['desktop']['App']['GenerateModel'](arg1, arg2);
}

export function GenerateQARegressionSourcePatch(arg1) {
  return window['go']['desktop']['App']['GenerateQARegressionSourcePatch'](arg1);
}

export function GenerateQARegressionTestDraft(arg1) {
  return window['go']['desktop']['App']['GenerateQARegressionTestDraft'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['desktop']['App']['GetConversation'](arg1);
}

export function GrantWorkspace(arg1, arg2) {
  return window['go']['desktop']['App']['GrantWorkspace'](arg1, arg2);
}

export function HeartbeatStatus() {
  return window['go']['desktop']['App']['HeartbeatStatus']();
}

export function ImportSkill(arg1) {
  return window['go']['desktop']['App']['ImportSkill'](arg1);
}

export function ImproveSkillFromSession(arg1, arg2) {
  return window['go']['desktop']['App']['ImproveSkillFromSession'](arg1, arg2);
}

export function IndexEmbeddings() {
  return window['go']['desktop']['App']['IndexEmbeddings']();
}

export function IngestDocuments(arg1) {
  return window['go']['desktop']['App']['IngestDocuments'](arg1);
}

export function InspectExtension(arg1) {
  return window['go']['desktop']['App']['InspectExtension'](arg1);
}

export function InstallDomainPack(arg1) {
  return window['go']['desktop']['App']['InstallDomainPack'](arg1);
}

export function InstallDomainPackTemplate(arg1) {
  return window['go']['desktop']['App']['InstallDomainPackTemplate'](arg1);
}

export function InstallGeneratedConnector(arg1) {
  return window['go']['desktop']['App']['InstallGeneratedConnector'](arg1);
}

export function InternetCache() {
  return window['go']['desktop']['App']['InternetCache']();
}

export function InternetCrawl(arg1) {
  return window['go']['desktop']['App']['InternetCrawl'](arg1);
}

export function InternetCrawlRun(arg1) {
  return window['go']['desktop']['App']['InternetCrawlRun'](arg1);
}

export function InternetCrawls(arg1) {
  return window['go']['desktop']['App']['InternetCrawls'](arg1);
}

export function InternetFetch(arg1) {
  return window['go']['desktop']['App']['InternetFetch'](arg1);
}

export function InternetHead(arg1) {
  return window['go']['desktop']['App']['InternetHead'](arg1);
}

export function InternetRequests(arg1) {
  return window['go']['desktop']['App']['InternetRequests'](arg1);
}

export function InternetSearch(arg1) {
  return window['go']['desktop']['App']['InternetSearch'](arg1);
}

export function InternetStatus() {
  return window['go']['desktop']['App']['InternetStatus']();
}

export function JobRuns(arg1) {
  return window['go']['desktop']['App']['JobRuns'](arg1);
}

export function JobStatus() {
  return window['go']['desktop']['App']['JobStatus']();
}

export function KnowledgeStatus() {
  return window['go']['desktop']['App']['KnowledgeStatus']();
}

export function LearningReport() {
  return window['go']['desktop']['App']['LearningReport']();
}

export function ListConnectors() {
  return window['go']['desktop']['App']['ListConnectors']();
}

export function ListConversations(arg1) {
  return window['go']['desktop']['App']['ListConversations'](arg1);
}

export function ListDocumentInventory(arg1) {
  return window['go']['desktop']['App']['ListDocumentInventory'](arg1);
}

export function ListDomainPackSkills() {
  return window['go']['desktop']['App']['ListDomainPackSkills']();
}

export function ListDomainPackTemplates() {
  return window['go']['desktop']['App']['ListDomainPackTemplates']();
}

export function ListDomainPacks() {
  return window['go']['desktop']['App']['ListDomainPacks']();
}

export function ListExtensions() {
  return window['go']['desktop']['App']['ListExtensions']();
}

export function ListGeneratedConnectors() {
  return window['go']['desktop']['App']['ListGeneratedConnectors']();
}

export function ListJobs() {
  return window['go']['desktop']['App']['ListJobs']();
}

export function ListKnowledgeEntities(arg1, arg2) {
  return window['go']['desktop']['App']['ListKnowledgeEntities'](arg1, arg2);
}

export function ListKnowledgeReviewItems(arg1, arg2) {
  return window['go']['desktop']['App']['ListKnowledgeReviewItems'](arg1, arg2);
}

export function ListMemories(arg1) {
  return window['go']['desktop']['App']['ListMemories'](arg1);
}

export function ListModelProfiles() {
  return window['go']['desktop']['App']['ListModelProfiles']();
}

export function ListModels() {
  return window['go']['desktop']['App']['ListModels']();
}

export function ListNotifications(arg1, arg2) {
  return window['go']['desktop']['App']['ListNotifications'](arg1, arg2);
}

export function ListReplayTraces(arg1) {
  return window['go']['desktop']['App']['ListReplayTraces'](arg1);
}

export function ListSkills() {
  return window['go']['desktop']['App']['ListSkills']();
}

export function ListToolRuns(arg1) {
  return window['go']['desktop']['App']['ListToolRuns'](arg1);
}

export function ListWorkspaceGrants() {
  return window['go']['desktop']['App']['ListWorkspaceGrants']();
}

export function MarkNotificationRead(arg1) {
  return window['go']['desktop']['App']['MarkNotificationRead'](arg1);
}

export function OpsStatus(arg1, arg2) {
  return window['go']['desktop']['App']['OpsStatus'](arg1, arg2);
}

export function PickDocumentFile(arg1) {
  return window['go']['desktop']['App']['PickDocumentFile'](arg1);
}

export function PickWorkspaceFolder(arg1) {
  return window['go']['desktop']['App']['PickWorkspaceFolder'](arg1);
}

export function PinMemory(arg1) {
  return window['go']['desktop']['App']['PinMemory'](arg1);
}

export function PlanFileWrite(arg1) {
  return window['go']['desktop']['App']['PlanFileWrite'](arg1);
}

export function PlanQARegressionSourceWrite(arg1) {
  return window['go']['desktop']['App']['PlanQARegressionSourceWrite'](arg1);
}

export function PolicyStatus() {
  return window['go']['desktop']['App']['PolicyStatus']();
}

export function PreviewModelProfile(arg1) {
  return window['go']['desktop']['App']['PreviewModelProfile'](arg1);
}

export function PromoteQARegressionSuggestion(arg1) {
  return window['go']['desktop']['App']['PromoteQARegressionSuggestion'](arg1);
}

export function ProposeCapability(arg1) {
  return window['go']['desktop']['App']['ProposeCapability'](arg1);
}

export function ProposeExtension(arg1) {
  return window['go']['desktop']['App']['ProposeExtension'](arg1);
}

export function PruneMissingDocuments(arg1) {
  return window['go']['desktop']['App']['PruneMissingDocuments'](arg1);
}

export function QAReview(arg1) {
  return window['go']['desktop']['App']['QAReview'](arg1);
}

export function RecordPermissionDecision(arg1) {
  return window['go']['desktop']['App']['RecordPermissionDecision'](arg1);
}

export function RegisterExtension(arg1) {
  return window['go']['desktop']['App']['RegisterExtension'](arg1);
}

export function RenameConversation(arg1, arg2) {
  return window['go']['desktop']['App']['RenameConversation'](arg1, arg2);
}

export function RepairKnowledgeEvidence() {
  return window['go']['desktop']['App']['RepairKnowledgeEvidence']();
}

export function ReviewDomainPack(arg1) {
  return window['go']['desktop']['App']['ReviewDomainPack'](arg1);
}

export function ReviewDomainPackTemplate(arg1) {
  return window['go']['desktop']['App']['ReviewDomainPackTemplate'](arg1);
}

export function ReviewExtension(arg1) {
  return window['go']['desktop']['App']['ReviewExtension'](arg1);
}

export function ReviewQARegressionSuggestion(arg1) {
  return window['go']['desktop']['App']['ReviewQARegressionSuggestion'](arg1);
}

export function RevokeWorkspaceGrant(arg1) {
  return window['go']['desktop']['App']['RevokeWorkspaceGrant'](arg1);
}

export function RollbackExtension(arg1) {
  return window['go']['desktop']['App']['RollbackExtension'](arg1);
}

export function RunDueJobs() {
  return window['go']['desktop']['App']['RunDueJobs']();
}

export function RunExtension(arg1) {
  return window['go']['desktop']['App']['RunExtension'](arg1);
}

export function RunJob(arg1) {
  return window['go']['desktop']['App']['RunJob'](arg1);
}

export function SaveCorrection(arg1) {
  return window['go']['desktop']['App']['SaveCorrection'](arg1);
}

export function SaveKnowledgeEdge(arg1) {
  return window['go']['desktop']['App']['SaveKnowledgeEdge'](arg1);
}

export function SaveKnowledgeEntity(arg1) {
  return window['go']['desktop']['App']['SaveKnowledgeEntity'](arg1);
}

export function SaveModelProfile(arg1) {
  return window['go']['desktop']['App']['SaveModelProfile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['desktop']['App']['SaveSettings'](arg1);
}

export function SearchDocuments(arg1) {
  return window['go']['desktop']['App']['SearchDocuments'](arg1);
}

export function SearchMemory(arg1) {
  return window['go']['desktop']['App']['SearchMemory'](arg1);
}

export function SetConversationStarred(arg1, arg2) {
  return window['go']['desktop']['App']['SetConversationStarred'](arg1, arg2);
}

export function SetDomainPackEnabled(arg1, arg2) {
  return window['go']['desktop']['App']['SetDomainPackEnabled'](arg1, arg2);
}

export function SetExtensionEnabled(arg1, arg2) {
  return window['go']['desktop']['App']['SetExtensionEnabled'](arg1, arg2);
}

export function SetGeneratedConnectorEnabled(arg1) {
  return window['go']['desktop']['App']['SetGeneratedConnectorEnabled'](arg1);
}

export function SetJobEnabled(arg1) {
  return window['go']['desktop']['App']['SetJobEnabled'](arg1);
}

export function SetKnowledgeEnabled(arg1) {
  return window['go']['desktop']['App']['SetKnowledgeEnabled'](arg1);
}

export function SetModelRole(arg1, arg2) {
  return window['go']['desktop']['App']['SetModelRole'](arg1, arg2);
}

export function SetModelRoleProvider(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['SetModelRoleProvider'](arg1, arg2, arg3, arg4);
}

export function SetPolicyMode(arg1) {
  return window['go']['desktop']['App']['SetPolicyMode'](arg1);
}

export function SetSkillEnabled(arg1, arg2) {
  return window['go']['desktop']['App']['SetSkillEnabled'](arg1, arg2);
}

export function Settings() {
  return window['go']['desktop']['App']['Settings']();
}

export function SetupState() {
  return window['go']['desktop']['App']['SetupState']();
}

export function ShowExtension(arg1) {
  return window['go']['desktop']['App']['ShowExtension'](arg1);
}

export function ShowModel(arg1) {
  return window['go']['desktop']['App']['ShowModel'](arg1);
}

export function ShowModelProfile(arg1) {
  return window['go']['desktop']['App']['ShowModelProfile'](arg1);
}

export function Status() {
  return window['go']['desktop']['App']['Status']();
}

export function StopGeneration() {
  return window['go']['desktop']['App']['StopGeneration']();
}

export function SuggestDocumentPaths(arg1, arg2) {
  return window['go']['desktop']['App']['SuggestDocumentPaths'](arg1, arg2);
}

export function TestExtension(arg1) {
  return window['go']['desktop']['App']['TestExtension'](arg1);
}

export function ToolCatalog(arg1) {
  return window['go']['desktop']['App']['ToolCatalog'](arg1);
}

export function UninstallDomainPack(arg1) {
  return window['go']['desktop']['App']['UninstallDomainPack'](arg1);
}

export function UpdateJobInput(arg1) {
  return window['go']['desktop']['App']['UpdateJobInput'](arg1);
}

export function UploadChatAttachment(arg1) {
  return window['go']['desktop']['App']['UploadChatAttachment'](arg1);
}

export function ValidateExtension(arg1) {
  return window['go']['desktop']['App']['ValidateExtension'](arg1);
}

export function ValidateSkill(arg1) {
  return window['go']['desktop']['App']['ValidateSkill'](arg1);
}

export function WriteMemory(arg1) {
  return window['go']['desktop']['App']['WriteMemory'](arg1);
}
