// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {learning} from '../models';
import {scheduler} from '../models';
import {connectors} from '../models';
import {notifications} from '../models';
import {replay} from '../models';
import {extensions} from '../models';
import {agent} from '../models';
import {heartbeat} from '../models';
import {domainpacks} from '../models';
import {internet} from '../models';
import {workflows} from '../models';
import {modelprofiles} from '../models';
import {models} from '../models';
import {server} from '../models';

export function ApplyCapability(arg1:desktop.CapabilityApplyInput):Promise<desktop.CapabilityApplyResult>;

export function ApplyFileWrite(arg1:desktop.FileWriteInput):Promise<desktop.FileWriteApplyResult>;

export function ApplyKnowledgeReviewBatch(arg1:desktop.KnowledgeReviewBatchInput):Promise<desktop.KnowledgeReviewBatchResult>;

export function ApplyModelProfile(arg1:desktop.ModelProfileApplyInput):Promise<desktop.ModelProfileResult>;

export function ApplyQARegressionSourceWrite(arg1:learning.QARegressionSourceWriteRequest):Promise<desktop.QARegressionSourceWriteApplyResult>;

export function ApproveQARegressionSourcePatchApplyPlan(arg1:learning.QARegressionSourcePatchApplyPlanRequest):Promise<learning.QARegressionSourcePatchApplyPlanRecord>;

export function ApproveQARegressionTestDraft(arg1:learning.QARegressionApprovalRequest):Promise<learning.QARegressionApprovedRecord>;

export function ArchiveJob(arg1:desktop.JobArchiveInput):Promise<scheduler.Job>;

export function Ask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<desktop.AskResult>;

export function Chat(arg1:string,arg2:string):Promise<desktop.ChatResult>;

export function CompleteSetup(arg1:desktop.SetupInput):Promise<desktop.SetupState>;

export function ConnectorRegistry():Promise<Array<connectors.RegistryEntry>>;

export function CreateJob(arg1:desktop.JobCreateInput):Promise<scheduler.Job>;

export function CreateSkillFromSession(arg1:string):Promise<desktop.SkillActionResult>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteExtension(arg1:string):Promise<desktop.ExtensionActionResult>;

export function DeleteMemory(arg1:string):Promise<void>;

export function DismissNotification(arg1:string):Promise<notifications.Notification>;

export function DraftKnowledgeProposal(arg1:desktop.KnowledgeProposalInput):Promise<desktop.KnowledgeProposalResult>;

export function DraftModelProfileFromConversation(arg1:desktop.ModelProfileDraftInput):Promise<desktop.ModelProfileResult>;

export function EditUserMessage(arg1:string,arg2:string):Promise<desktop.ConversationMessageResult>;

export function ExplainReplayTrace(arg1:string):Promise<replay.TraceExplanation>;

export function ExportSkill(arg1:string,arg2:string):Promise<desktop.SkillActionResult>;

export function ExportTrajectory(arg1:string):Promise<learning.Trajectory>;

export function ExtensionFailures(arg1:number):Promise<Array<extensions.FailureTrend>>;

export function GenerateCapability(arg1:desktop.CapabilityGenerateInput):Promise<agent.CapabilityGenerationResult>;

export function GenerateExtension(arg1:desktop.ExtensionGenerateInput):Promise<extensions.GenerationResult>;

export function GenerateModel(arg1:string,arg2:string):Promise<desktop.ModelGenerateResult>;

export function GenerateQARegressionSourcePatch(arg1:learning.QARegressionSourcePatchRequest):Promise<learning.QARegressionSourcePatchRecord>;

export function GenerateQARegressionTestDraft(arg1:learning.QARegressionTestDraftRequest):Promise<learning.QARegressionTestDraftRecord>;

export function GetConversation(arg1:string):Promise<desktop.ConversationDetailResult>;

export function GrantWorkspace(arg1:string,arg2:string):Promise<desktop.WorkspaceGrantResult>;

export function HeartbeatStatus():Promise<heartbeat.Report>;

export function ImportSkill(arg1:string):Promise<desktop.SkillActionResult>;

export function ImproveSkillFromSession(arg1:string,arg2:string):Promise<desktop.SkillActionResult>;

export function IndexEmbeddings():Promise<desktop.EmbeddingIndexSummary>;

export function IngestDocuments(arg1:string):Promise<desktop.IngestSummary>;

export function InspectExtension(arg1:string):Promise<extensions.PackageInspection>;

export function InstallDomainPack(arg1:string):Promise<domainpacks.PackStatus>;

export function InstallDomainPackTemplate(arg1:string):Promise<domainpacks.PackStatus>;

export function InstallGeneratedConnector(arg1:connectors.GeneratedInstallInput):Promise<connectors.GeneratedActionResult>;

export function InternetCache():Promise<Array<internet.CacheSummary>>;

export function InternetCrawl(arg1:desktop.InternetCrawlInput):Promise<internet.CrawlResult>;

export function InternetCrawlRun(arg1:string):Promise<internet.CrawlRunRecord>;

export function InternetCrawls(arg1:number):Promise<Array<internet.CrawlRunRecord>>;

export function InternetFetch(arg1:desktop.InternetFetchInput):Promise<internet.FetchResult>;

export function InternetHead(arg1:desktop.InternetFetchInput):Promise<internet.FetchResult>;

export function InternetRequests(arg1:number):Promise<Array<internet.RequestRecord>>;

export function InternetSearch(arg1:desktop.InternetSearchInput):Promise<internet.SearchResult>;

export function InternetStatus():Promise<internet.Status>;

export function JobRuns(arg1:number):Promise<Array<scheduler.JobRun>>;

export function JobStatus():Promise<scheduler.Status>;

export function KnowledgeStatus():Promise<desktop.KnowledgeStatus>;

export function LearningReport():Promise<learning.Report>;

export function ListConnectors():Promise<Array<connectors.Status>>;

export function ListConversations(arg1:number):Promise<Array<desktop.ConversationResult>>;

export function ListDocumentInventory(arg1:number):Promise<Array<desktop.DocumentInventoryResult>>;

export function ListDomainPackSkills():Promise<Array<desktop.DomainPackSkillStatus>>;

export function ListDomainPackTemplates():Promise<Array<workflows.TemplateSummary>>;

export function ListDomainPacks():Promise<Array<domainpacks.PackStatus>>;

export function ListExtensions():Promise<Array<extensions.Status>>;

export function ListGeneratedConnectors():Promise<Array<connectors.GeneratedEntry>>;

export function ListJobs():Promise<Array<scheduler.Job>>;

export function ListKnowledgeEntities(arg1:string,arg2:number):Promise<Array<desktop.KnowledgeEntityResult>>;

export function ListKnowledgeReviewItems(arg1:string,arg2:number):Promise<Array<desktop.KnowledgeReviewItemResult>>;

export function ListMemories(arg1:number):Promise<Array<desktop.MemoryResult>>;

export function ListModelProfiles():Promise<Array<modelprofiles.Profile>>;

export function ListModels():Promise<Array<models.ModelInfo>>;

export function ListNotifications(arg1:number,arg2:boolean):Promise<Array<notifications.Notification>>;

export function ListReplayTraces(arg1:number):Promise<Array<replay.TraceFile>>;

export function ListSkills():Promise<Array<desktop.SkillSummary>>;

export function ListToolRuns(arg1:number):Promise<Array<desktop.ToolRunResult>>;

export function ListWorkspaceGrants():Promise<Array<desktop.WorkspaceGrantResult>>;

export function MarkNotificationRead(arg1:string):Promise<notifications.Notification>;

export function OpsStatus(arg1:boolean,arg2:number):Promise<server.OpsStatus>;

export function PickDocumentFile(arg1:string):Promise<desktop.DocumentSourceResult>;

export function PickWorkspaceFolder(arg1:string):Promise<desktop.WorkspaceGrantResult>;

export function PinMemory(arg1:string):Promise<void>;

export function PlanFileWrite(arg1:desktop.FileWriteInput):Promise<desktop.FileWritePlanResult>;

export function PlanQARegressionSourceWrite(arg1:learning.QARegressionSourceWriteRequest):Promise<desktop.QARegressionSourceWritePlanResult>;

export function PolicyStatus():Promise<desktop.PolicyStatusResult>;

export function PreviewModelProfile(arg1:desktop.ModelProfileInput):Promise<desktop.ModelProfileResult>;

export function PromoteQARegressionSuggestion(arg1:learning.QARegressionPromotionRequest):Promise<learning.QARegressionPromotionArtifact>;

export function ProposeCapability(arg1:desktop.ExtensionProposalInput):Promise<agent.CapabilityGapProposal>;

export function ProposeExtension(arg1:desktop.ExtensionProposalInput):Promise<extensions.Proposal>;

export function PruneMissingDocuments(arg1:boolean):Promise<desktop.DocumentPruneResult>;

export function QAReview(arg1:number):Promise<learning.QAReview>;

export function RecordPermissionDecision(arg1:desktop.PermissionDecisionInput):Promise<desktop.PermissionDecisionResult>;

export function RegisterExtension(arg1:string):Promise<extensions.TestResult>;

export function RenameConversation(arg1:string,arg2:string):Promise<desktop.ConversationResult>;

export function RepairKnowledgeEvidence():Promise<desktop.KnowledgeRepairResult>;

export function ReviewDomainPack(arg1:string):Promise<domainpacks.PackReview>;

export function ReviewDomainPackTemplate(arg1:string):Promise<domainpacks.PackReview>;

export function ReviewExtension(arg1:string):Promise<extensions.Review>;

export function ReviewQARegressionSuggestion(arg1:learning.QARegressionReviewRequest):Promise<learning.QARegressionReviewRecord>;

export function RevokeWorkspaceGrant(arg1:string):Promise<desktop.WorkspaceGrantResult>;

export function RollbackExtension(arg1:desktop.ExtensionRollbackInput):Promise<extensions.RollbackResult>;

export function RunDueJobs():Promise<scheduler.TickResult>;

export function RunExtension(arg1:desktop.ExtensionRunInput):Promise<extensions.RunResult>;

export function RunJob(arg1:desktop.JobRunInput):Promise<scheduler.JobRun>;

export function SaveCorrection(arg1:desktop.LearningCorrectionInput):Promise<desktop.MemoryResult>;

export function SaveKnowledgeEdge(arg1:desktop.KnowledgeEdgeInput):Promise<desktop.KnowledgeEdgeResult>;

export function SaveKnowledgeEntity(arg1:desktop.KnowledgeEntityInput):Promise<desktop.KnowledgeEntityResult>;

export function SaveModelProfile(arg1:desktop.ModelProfileInput):Promise<desktop.ModelProfileResult>;

export function SaveSettings(arg1:desktop.SettingsInput):Promise<desktop.SettingsView>;

export function SearchDocuments(arg1:string):Promise<Array<desktop.DocumentResult>>;

export function SearchMemory(arg1:string):Promise<Array<desktop.MemoryResult>>;

export function SetConversationStarred(arg1:string,arg2:boolean):Promise<desktop.ConversationResult>;

export function SetDomainPackEnabled(arg1:string,arg2:boolean):Promise<domainpacks.PackStatus>;

export function SetExtensionEnabled(arg1:string,arg2:boolean):Promise<desktop.ExtensionActionResult>;

export function SetGeneratedConnectorEnabled(arg1:desktop.GeneratedConnectorEnabledInput):Promise<connectors.GeneratedActionResult>;

export function SetJobEnabled(arg1:desktop.JobEnabledInput):Promise<scheduler.Job>;

export function SetKnowledgeEnabled(arg1:desktop.KnowledgeEnabledInput):Promise<desktop.KnowledgeStatus>;

export function SetModelRole(arg1:string,arg2:string):Promise<void>;

export function SetModelRoleProvider(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetPolicyMode(arg1:string):Promise<desktop.PolicyStatusResult>;

export function SetSkillEnabled(arg1:string,arg2:boolean):Promise<desktop.SkillActionResult>;

export function Settings():Promise<desktop.SettingsView>;

export function SetupState():Promise<desktop.SetupState>;

export function ShowExtension(arg1:string):Promise<extensions.Detail>;

export function ShowModel(arg1:string):Promise<models.ModelDetails>;

export function ShowModelProfile(arg1:string):Promise<desktop.ModelProfileResult>;

export function Status():Promise<desktop.Status>;

export function StopGeneration():Promise<void>;

export function SuggestDocumentPaths(arg1:string,arg2:number):Promise<Array<desktop.DocumentPathSuggestionResult>>;

export function TestExtension(arg1:string):Promise<extensions.TestResult>;

export function ToolCatalog(arg1:string):Promise<Array<desktop.ToolCatalogEntryResult>>;

export function UninstallDomainPack(arg1:string):Promise<domainpacks.PackStatus>;

export function UpdateJobInput(arg1:desktop.JobInputUpdateInput):Promise<scheduler.Job>;

export function UploadChatAttachment(arg1:desktop.ChatAttachmentUploadInput):Promise<desktop.ChatAttachmentUploadResult>;

export function ValidateExtension(arg1:string):Promise<desktop.ExtensionActionResult>;

export function ValidateSkill(arg1:string):Promise<desktop.SkillActionResult>;

export function WriteMemory(arg1:desktop.MemoryWriteInput):Promise<desktop.MemoryResult>;
